# Generated by Django 3.2.5 on 2022-05-13 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('uid', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('User_id', models.CharField(max_length=255)),
                ('booking_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('sid', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('booking_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('User_id', models.CharField(max_length=255)),
                ('Room_id', models.CharField(max_length=255)),
                ('from_date', models.DateField()),
                ('end_date', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('invites', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('room_no', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
    ]
